# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestCompler():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_compler(self):
        self.driver.get("https://demo.constantadev.tech/fms3/red/dev/")
        self.driver.implicitly_wait(10)
        self.driver.set_window_size(1680, 948)
        self.driver.find_element(By.CSS_SELECTOR, ".c-header__icon_menu path").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-user__button:nth-child(2) > .ui-button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".is-active > .ui-tab__inner").click()
        self.driver.find_element(By.ID, "login").click()
        self.driver.find_element(By.ID, "login").send_keys("11")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("rtrtrt11")
        self.driver.find_element(By.CSS_SELECTOR, ".h-grow-1 > .ui-button").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".h-grow-1 > .ui-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()